# Generated by Django 4.1.5 on 2023-01-13 20:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='users_voted_comment',
            field=models.ManyToManyField(blank=True, related_name='users_voted_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_voted_post',
            field=models.ManyToManyField(blank=True, related_name='users_voted_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
