# Generated by Django 4.1.5 on 2023-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_spotify_access_token_user_spotify_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
