# Generated by Django 4.1.5 on 2023-01-13 20:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_users_voted_comment_post_users_voted_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='users_voted_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='users_voted_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='users_downvoted_comment',
            field=models.ManyToManyField(blank=True, related_name='users_downvoted_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='users_upvoted_comment',
            field=models.ManyToManyField(blank=True, related_name='users_upvoted_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_downvoted_post',
            field=models.ManyToManyField(blank=True, related_name='users_downvoted_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='users_upvoted_post',
            field=models.ManyToManyField(blank=True, related_name='users_upvoted_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
