# Generated by Django 4.1.5 on 2023-01-20 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_comment_users_voted_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users_downvoted_comment',
            new_name='users_downvoted',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='users_upvoted_comment',
            new_name='users_upvoted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='users_downvoted_post',
            new_name='users_downvoted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='users_upvoted_post',
            new_name='users_upvoted',
        ),
    ]
