# Generated by Django 4.1.5 on 2023-02-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_user_spotify_token_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='spotify_access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='spotify_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
