# Generated by Django 4.1.5 on 2023-01-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_is_reply_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='children_comments',
        ),
    ]
